/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Color = string;
export interface CustomizelyProject {
  'created' : Timestamp,
  'owner' : Principal,
  'name' : string,
  'designElements' : Array<DesignElement>,
  'baseColor' : Color,
  'productType' : ProductType,
  'projectId' : string,
}
export interface DesignElement {
  'content' : string,
  'color' : Color,
  'size' : Size,
  'position' : Position,
  'elementType' : DesignElementType,
}
export type DesignElementType = { 'text' : null } |
  { 'shape' : null } |
  { 'image' : null };
export interface Position { 'x' : number, 'y' : number }
export type ProductType = { 'hat' : null } |
  { 'mug' : null } |
  { 'custom' : null } |
  { 'tShirt' : null };
export interface Size { 'height' : number, 'width' : number }
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAllProjects' : ActorMethod<[], Array<CustomizelyProject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProjects' : ActorMethod<[], Array<CustomizelyProject>>,
  'getProject' : ActorMethod<[string], [] | [CustomizelyProject]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProject' : ActorMethod<
    [string, string, Color, Array<DesignElement>, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];