/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Color = IDL.Text;
export const Size = IDL.Record({
  'height' : IDL.Float64,
  'width' : IDL.Float64,
});
export const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const DesignElementType = IDL.Variant({
  'text' : IDL.Null,
  'shape' : IDL.Null,
  'image' : IDL.Null,
});
export const DesignElement = IDL.Record({
  'content' : IDL.Text,
  'color' : Color,
  'size' : Size,
  'position' : Position,
  'elementType' : DesignElementType,
});
export const ProductType = IDL.Variant({
  'hat' : IDL.Null,
  'mug' : IDL.Null,
  'custom' : IDL.Null,
  'tShirt' : IDL.Null,
});
export const CustomizelyProject = IDL.Record({
  'created' : Timestamp,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'designElements' : IDL.Vec(DesignElement),
  'baseColor' : Color,
  'productType' : ProductType,
  'projectId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(CustomizelyProject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProjects' : IDL.Func([], [IDL.Vec(CustomizelyProject)], ['query']),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(CustomizelyProject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProject' : IDL.Func(
      [IDL.Text, IDL.Text, Color, IDL.Vec(DesignElement), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Color = IDL.Text;
  const Size = IDL.Record({ 'height' : IDL.Float64, 'width' : IDL.Float64 });
  const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const DesignElementType = IDL.Variant({
    'text' : IDL.Null,
    'shape' : IDL.Null,
    'image' : IDL.Null,
  });
  const DesignElement = IDL.Record({
    'content' : IDL.Text,
    'color' : Color,
    'size' : Size,
    'position' : Position,
    'elementType' : DesignElementType,
  });
  const ProductType = IDL.Variant({
    'hat' : IDL.Null,
    'mug' : IDL.Null,
    'custom' : IDL.Null,
    'tShirt' : IDL.Null,
  });
  const CustomizelyProject = IDL.Record({
    'created' : Timestamp,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'designElements' : IDL.Vec(DesignElement),
    'baseColor' : Color,
    'productType' : ProductType,
    'projectId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(CustomizelyProject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProjects' : IDL.Func([], [IDL.Vec(CustomizelyProject)], ['query']),
    'getProject' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomizelyProject)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProject' : IDL.Func(
        [IDL.Text, IDL.Text, Color, IDL.Vec(DesignElement), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };